from phoenix.framework.agent.core.loop import AgentLoop
import json
import os
import asyncio

from .tasks import TASK_FILE, _load_tasks, _mark_task

class AshbornLoop(AgentLoop):
    """
    Task-file driven agent loop:
      - Reads .ashborn_tasks.json generated by AshbornThinker
      - Executes tasks sorted by priority
      - Marks each task done/failed in the file
      - Deletes the file after all tasks are processed
    """

    MAX_RETRIES_PER_TASK = 2
    MAX_TOTAL_ACTIONS = 30

    def _schedule_background(self, coro):
        task = asyncio.create_task(coro)
        self._background_tasks.add(task)

        def _on_done(t):
            self._background_tasks.discard(t)
            try:
                _ = t.exception()
            except Exception:
                pass

        task.add_done_callback(_on_done)

    def _get_pending_tasks(self) -> list:
        """Load and return tasks sorted by priority that are still pending."""
        try:
            data = _load_tasks()
            return sorted(
                [t for t in data["tasks"] if t["status"] == "pending"],
                key=lambda t: t.get("priority", 99)
            )
        except Exception:
            return []

    def _has_task_file(self) -> bool:
        return os.path.exists(TASK_FILE)

    async def run(self, prompt: str, memory, session_id: str, mode: str = "auto", **kwargs) -> str:
        # FAST ANSWER MODE
        if mode == "fast_ans":
            context = await memory.get_full_context(session_id, query=prompt)
            system_prompt = "You are ASHBORN. Give a concise, direct answer to the user's question."
            full_prompt = f"{system_prompt}\n\nContext:\n{context}\n\nUser: {prompt}"
            ans = await self.planner.llm.generate(full_prompt, session_id=session_id)
            await memory.add_interaction(session_id, "assistant", ans)
            return ans

        # Step 1: Think — generates .ashborn_tasks.json
        objective_meta = await self.thinker.analyze(prompt, memory, session_id)
        memory.session.set("current_objective", objective_meta)

        # Step 2: Analyze workspace concurrently (best-effort)
        try:
            analysis = await self.analyzer.analyze_workspace(prompt)
            memory.session.set("project_analysis", analysis)
        except Exception:
            pass

        await memory.add_interaction(session_id, "system", f"Task breakdown: {objective_meta}")

        accumulated_results = ""
        task_summaries = []
        total_actions = 0

        # Step 3: Execute tasks by priority
        while self._has_task_file() and total_actions < self.MAX_TOTAL_ACTIONS:
            pending = self._get_pending_tasks()
            if not pending:
                break

            task = pending[0]

            for attempt in range(self.MAX_RETRIES_PER_TASK):
                plan = await self.planner.plan_task(task, accumulated_results)
                actions = plan.get("actions", [])

                # Skip if planner says finish for this task
                if any(a.get("tool") == "finish" for a in actions):
                    _mark_task(task["id"], "done")
                    task_summaries.append(f"✓ [{task['priority']}] {task['title']}: skipped (already done)")
                    break

                action_result = await self.actor.execute(plan)
                total_actions += len([a for a in actions if a.get("tool") != "finish"])

                reflection = await self.reflector.reflect(task["description"], plan, action_result)

                accumulated_results += (
                    f"\nTask '{task['title']}' (attempt {attempt + 1}):\n"
                    f"  Result: {action_result}\n"
                    f"  Reflection: {reflection['reflection']}\n"
                )

                self._schedule_background(memory.add_interaction(
                    session_id, "system",
                    f"Task: {task['title']} | Result: {action_result} | Reflection: {reflection['reflection']}"
                ))

                if reflection["is_complete"]:
                    _mark_task(task["id"], "done")
                    task_summaries.append(f"✓ [{task['priority']}] {task['title']}")
                    break
                elif attempt == self.MAX_RETRIES_PER_TASK - 1:
                    _mark_task(task["id"], "failed")
                    task_summaries.append(f"✗ [{task['priority']}] {task['title']}: failed after {self.MAX_RETRIES_PER_TASK} attempts")

        # Step 4: Cleanup
        if self._has_task_file():
            try:
                os.remove(TASK_FILE)
            except Exception:
                pass

        # Step 5: Synthesize final answer
        summary = "\n".join(task_summaries) if task_summaries else "No tasks were executed."
        final_answer = f"**Ashborn Task Execution Complete**\n\n{summary}\n\n---\n{accumulated_results.strip()}"
        await memory.add_interaction(session_id, "assistant", final_answer)
        return final_answer

    async def run_stream(self, prompt: str, memory, session_id: str, mode: str = "auto", **kwargs):
        # FAST ANSWER MODE: Bypass the heavy task loop for quick queries
        if mode == "fast_ans":
            yield {"type": "status", "role": "analyzer", "content": "⚡ Fast Answer mode active..."}
            context = await memory.get_full_context(session_id, query=prompt)
            system_prompt = "You are ASHBORN. Give a concise, direct answer to the user's question."
            full_prompt = f"{system_prompt}\n\nContext:\n{context}\n\nUser: {prompt}"
            
            async for chunk in self.planner.llm.generate_stream(full_prompt, session_id=session_id):
                yield {"type": "chunk", "content": chunk}
            
            await memory.add_interaction(session_id, "assistant", "Fast answer generated.")
            return

        # Step 1+2: Think AND analyze workspace concurrently
        yield {"type": "status", "role": "thinker", "content": "🧠 Decomposing your request into tasks..."}
        analyze_task = asyncio.create_task(
            self.analyzer.analyze_workspace(prompt)
        )
        objective_meta = await self.thinker.analyze(prompt, memory, session_id)
        memory.session.set("current_objective", objective_meta)
        try:
            analysis = await asyncio.wait_for(analyze_task, timeout=5.0)
            memory.session.set("project_analysis", analysis)
        except Exception:
            pass

        task_count_str = ""
        if "(" in objective_meta:
            task_count_str = objective_meta.split("(")[1].split(")")[0]
        yield {"type": "status", "role": "thinker", "content": f"📋 {task_count_str}"}
        await memory.add_interaction(session_id, "system", f"Task breakdown: {objective_meta}")

        accumulated_results = ""
        task_summaries = []
        total_actions = 0
        task_number = 0

        # Step 3: Execute tasks by priority
        while self._has_task_file() and total_actions < self.MAX_TOTAL_ACTIONS:
            pending = self._get_pending_tasks()
            if not pending:
                break

            task = pending[0]
            task_number += 1

            try:
                all_tasks_count = len(_load_tasks().get("tasks", []))
            except Exception:
                all_tasks_count = "?"

            status_line = self.planner.task_status_line(task)
            yield {"type": "status", "role": "planner", "content": f"⚙ Task {task_number}/{all_tasks_count}: {task['title']}"}
            yield {"type": "chunk", "role": "planner", "content": f"\n**[P{task['priority']}] {task['title']}**\n_{status_line}_\n"}

            for attempt in range(self.MAX_RETRIES_PER_TASK):
                plan = await self.planner.plan_task(task, accumulated_results)
                actions = plan.get("actions", [])

                if any(a.get("tool") == "finish" for a in actions):
                    _mark_task(task["id"], "done")
                    task_summaries.append(f"✓ {task['title']}")
                    yield {"type": "chunk", "role": "planner", "content": f"  ↳ Skipped (already complete)\n"}
                    break

                yield {"type": "status", "role": "actor", "content": f"  Executing {len(actions)} action(s)..."}
                action_result = await self.actor.execute(plan)
                total_actions += len([a for a in actions if a.get("tool") != "finish"])

                reflection = await self.reflector.reflect(task["description"], plan, action_result)

                accumulated_results += (
                    f"\nTask '{task['title']}' (attempt {attempt + 1}):\n"
                    f"  Result: {action_result}\n"
                    f"  Reflection: {reflection['reflection']}\n"
                )

                self._schedule_background(memory.add_interaction(
                    session_id, "system",
                    f"Task: {task['title']} | Result: {action_result} | Reflection: {reflection['reflection']}"
                ))

                if reflection["is_complete"]:
                    _mark_task(task["id"], "done")
                    task_summaries.append(f"✓ {task['title']}")
                    yield {"type": "chunk", "role": "reflector", "content": f"  ↳ ✓ Done: {reflection['reflection']}\n"}
                    break
                else:
                    if attempt < self.MAX_RETRIES_PER_TASK - 1:
                        yield {"type": "chunk", "role": "reflector", "content": f"  ↳ ⚠ Retrying: {reflection['reflection']}\n"}
                    else:
                        _mark_task(task["id"], "failed")
                        task_summaries.append(f"✗ {task['title']}")
                        yield {"type": "chunk", "role": "reflector", "content": f"  ↳ ✗ Failed: {reflection['reflection']}\n"}

        # Step 4: Cleanup
        if self._has_task_file():
            yield {"type": "status", "content": "🗑 Cleaning up task file..."}
            try:
                os.remove(TASK_FILE)
            except Exception:
                pass

        # Step 5: Final summary
        summary_lines = "\n".join(task_summaries) if task_summaries else "No tasks were executed."
        yield {"type": "chunk", "content": f"\n\n---\n**All tasks complete!**\n\n{summary_lines}\n"}

        final_answer = f"Tasks complete:\n{summary_lines}\n\n{accumulated_results.strip()}"
        await memory.add_interaction(session_id, "assistant", final_answer)
